[package]
name = "fui-rs-demo-home"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only OR LicenseRef-EffinDom-Commercial"

[dependencies]
fui-rs = { path = "../.." }
fui-rs-demo-shared = { path = "../demo-shared" }
fui-rs-demo-universal = { path = "../demo-universal" }

[features]
default = ["web-route"]
web-route = []
native-runtime = [
  "fui-rs/native-runtime",
  "fui-rs-demo-shared/native-runtime",
  "fui-rs-demo-universal/native-runtime",
]

[lib]
name = "fui_rs_demo_home"
