[package]
name = "fui-rs-demo-shared"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only OR LicenseRef-EffinDom-Commercial"

[dependencies]
fui-rs = { path = "../.." }
fui-rs-demo-universal = { path = "../demo-universal" }

[target.'cfg(all(not(target_family = "wasm"), not(target_os = "windows")))'.dependencies]
ureq = { version = "2.12", default-features = false, features = ["tls"], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
ureq = { version = "2.12", default-features = false, features = ["native-tls"], optional = true }

[features]
native-runtime = ["fui-rs/native-runtime", "fui-rs-demo-universal/native-runtime", "dep:ureq"]

[lib]
name = "fui_rs_demo_shared"
