import type { CFunction, CHeader } from "../../shared/c-header";
import { fuiFetchHostImports } from "../../shared/fui-fetch-host";
import { emitRustEnum, valuesForEnumSpec } from "../../shared/enum-generation";
import { fuiHostImports } from "../../shared/fui-host";
import { canonicalEnumSpecs } from "../../shared/model/enum-specs";
import { emitRustWasmHostImport, emitRustWasmUiImport } from "./imports";
import { rustEnumBacking } from "./types";

export function emitFuiRsFfiFile(uiSource: CHeader, coreSource: CHeader, uiFunctions: readonly CFunction[]): string {
  const uiImports = uiFunctions.filter((fn) => fn.name.startsWith("ui_"));
  const blocks = [
    "// Generated by v2/abi/generate.ts strategy fui-rs-ffi.",
    "// Raw ABI imports, ABI enums, and non-wasm test doubles for FUI-RS.",
    "// Do not edit by hand.",
    "",
    "#![allow(dead_code)]",
    "#![allow(non_snake_case)]",
    "#![allow(clippy::too_many_arguments)]",
    "#![allow(clippy::missing_safety_doc)]",
    "",
    ...canonicalEnumSpecs.map((spec) => emitRustEnum(spec, valuesForEnumSpec(spec, uiSource, coreSource), rustEnumBacking(spec))),
    "",
    "#[cfg(any(target_arch = \"wasm32\", feature = \"native-runtime\"))]",
    "#[cfg_attr(target_arch = \"wasm32\", link(wasm_import_module = \"effindom_v2_ui\"))]",
    "unsafe extern \"C\" {",
    uiImports.map(emitRustWasmUiImport).join("\n"),
    "}",
    "",
    "#[cfg(any(target_arch = \"wasm32\", feature = \"native-runtime\"))]",
    "#[cfg_attr(target_arch = \"wasm32\", link(wasm_import_module = \"fui_host\"))]",
    "unsafe extern \"C\" {",
    fuiHostImports.map(emitRustWasmHostImport).join("\n"),
    "}",
    "",
    "#[cfg(any(target_arch = \"wasm32\", feature = \"native-runtime\"))]",
    "#[cfg_attr(target_arch = \"wasm32\", link(wasm_import_module = \"fui_fetch_host\"))]",
    "unsafe extern \"C\" {",
    fuiFetchHostImports.map(emitRustWasmHostImport).join("\n"),
    "}",
    "",
  ];
  return blocks.join("\n").replace(/\n{3,}/g, "\n\n");
}
