[workspace]
members = [
  "demo-home",
  "demo-immediate-drawing",
  "demo-page-registry",
  "demo-platform",
  "demo-shared",
  "demo-universal",
  "demo-stage4",
  "demo-stage5",
  "demo-worker",
  "demo-workbench",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
