import path from "node:path";

import { type GenerateContext, type GenerateStrategy, writeGeneratedFile } from "../../shared/core";
import { fuiHostEnums } from "../../shared/fui-host";

function emitNativeHostHeader(): string {
  const enums = fuiHostEnums.map((item) => [
    `typedef enum ${item.name} {`,
    ...item.members.map((member) => `    ${member.name} = ${member.value},`),
    `} ${item.name};`,
  ].join("\n"));
  return [
    "// Generated by v2/abi/generate.ts strategy native-host-header.",
    "// Do not edit by hand.",
    "#pragma once",
    "",
    ...enums,
    "",
  ].join("\n\n");
}

export class NativeHostHeaderStrategy implements GenerateStrategy {
  public readonly name = "native-host-header";

  public async run(context: GenerateContext): Promise<void> {
    const outputPath = path.join(context.repoRoot, "v2/abi/generated/fui_host_abi.h");
    await writeGeneratedFile(
      outputPath,
      emitNativeHostHeader(),
      context.check,
      `${path.relative(process.cwd(), outputPath)} is stale. Run npm run generate:abi from v2/fui-rs.`,
    );
  }
}
