import { promises as fs } from "node:fs";
import path from "node:path";
import { listHostEventMethods, type HostServiceTypeName } from "./registry";
import { loadModuleExport, snakeCaseIdentifier, sourcePathForHeader } from "./common";

function rustValueType(type: HostServiceTypeName): string {
  switch (type) {
    case "string":
      return "String";
    case "bool":
      return "bool";
    case "i32":
      return "i32";
    case "u32":
      return "u32";
    case "i64":
      return "i64";
    case "u64":
      return "u64";
    case "f64":
      return "f64";
    case "bytes":
      return "Vec<u8>";
    case "i32_array":
      return "Vec<i32>";
    case "u32_array":
      return "Vec<u32>";
    case "i64_array":
      return "Vec<i64>";
    case "u64_array":
      return "Vec<u64>";
    case "f64_array":
      return "Vec<f64>";
    case "void":
      return "()";
  }
}

function callbackType(args: readonly HostServiceTypeName[]): string {
  if (args.length === 0) {
    return "Box<dyn Fn()>";
  }
  return `Box<dyn Fn(${args.map((arg) => rustValueType(arg)).join(", ")})>`;
}

function emitExportArgs(args: readonly HostServiceTypeName[]): string {
  const parts: string[] = [];
  args.forEach((type, index) => {
    if (type === "string" || type === "bytes") {
      parts.push(`arg${String(index)}_ptr: *const u8`, `arg${String(index)}_len: u32`);
      return;
    }
    if (type === "i32_array" || type === "u32_array") {
      parts.push(`arg${String(index)}_ptr: *const u32`, `arg${String(index)}_len: u32`);
      return;
    }
    if (type === "i64_array" || type === "u64_array" || type === "f64_array") {
      parts.push(`arg${String(index)}_ptr: *const u64`, `arg${String(index)}_len: u32`);
      return;
    }
    parts.push(`arg${String(index)}: ${rustValueType(type)}`);
  });
  return parts.join(", ");
}

function emitDecodedArgs(args: readonly HostServiceTypeName[]): string[] {
  const lines: string[] = [];
  args.forEach((type, index) => {
    if (type === "string") {
      lines.push(
        `    let arg${String(index)} = if arg${String(index)}_ptr.is_null() || arg${String(index)}_len == 0 { String::new() } else { String::from_utf8_lossy(unsafe { std::slice::from_raw_parts(arg${String(index)}_ptr, arg${String(index)}_len as usize) }).into_owned() };`,
      );
      return;
    }
    if (type === "bytes") {
      lines.push(
        `    let arg${String(index)} = if arg${String(index)}_ptr.is_null() || arg${String(index)}_len == 0 { Vec::new() } else { unsafe { std::slice::from_raw_parts(arg${String(index)}_ptr, arg${String(index)}_len as usize) }.to_vec() };`,
      );
      return;
    }
    if (type === "i32_array") {
      lines.push(
        `    let arg${String(index)} = if arg${String(index)}_ptr.is_null() || arg${String(index)}_len == 0 { Vec::new() } else { unsafe { std::slice::from_raw_parts(arg${String(index)}_ptr as *const i32, arg${String(index)}_len as usize) }.to_vec() };`,
      );
      return;
    }
    if (type === "u32_array") {
      lines.push(
        `    let arg${String(index)} = if arg${String(index)}_ptr.is_null() || arg${String(index)}_len == 0 { Vec::new() } else { unsafe { std::slice::from_raw_parts(arg${String(index)}_ptr as *const u32, arg${String(index)}_len as usize) }.to_vec() };`,
      );
      return;
    }
    if (type === "i64_array") {
      lines.push(
        `    let arg${String(index)} = if arg${String(index)}_ptr.is_null() || arg${String(index)}_len == 0 { Vec::new() } else { unsafe { std::slice::from_raw_parts(arg${String(index)}_ptr as *const i64, arg${String(index)}_len as usize) }.to_vec() };`,
      );
      return;
    }
    if (type === "u64_array") {
      lines.push(
        `    let arg${String(index)} = if arg${String(index)}_ptr.is_null() || arg${String(index)}_len == 0 { Vec::new() } else { unsafe { std::slice::from_raw_parts(arg${String(index)}_ptr as *const u64, arg${String(index)}_len as usize) }.to_vec() };`,
      );
      return;
    }
    if (type === "f64_array") {
      lines.push(
        `    let arg${String(index)} = if arg${String(index)}_ptr.is_null() || arg${String(index)}_len == 0 { Vec::new() } else { unsafe { std::slice::from_raw_parts(arg${String(index)}_ptr as *const f64, arg${String(index)}_len as usize) }.to_vec() };`,
      );
    }
  });
  return lines;
}

export async function generateRustHostEventsFile(
  modulePath: string,
  exportName: string,
  outputPath: string,
): Promise<void> {
  const registry = await loadModuleExport(modulePath, exportName, "fui-rs-host-events-");
  const methods = listHostEventMethods(registry as never);
  const lines: string[] = [
    `// Generated by hostgen from ${sourcePathForHeader(modulePath)}#${exportName}.`,
    "// Do not edit by hand.",
    "",
    "#![allow(dead_code)]",
    "#![allow(non_snake_case)]",
    "",
    "use std::cell::RefCell;",
    "",
  ];
  methods.forEach((method) => {
    const handlerName = snakeCaseIdentifier(method.eventName);
    const callbackTy = callbackType(method.args);
    lines.push("thread_local! {");
    lines.push(
      `    static ${handlerName.toUpperCase()}_HANDLER: RefCell<Option<${callbackTy}>> = const { RefCell::new(None) };`,
    );
    lines.push("}");
    lines.push("");
    lines.push(
      `pub fn on_${handlerName}(callback: impl Fn(${method.args.map((arg) => rustValueType(arg)).join(", ")}) + 'static) {`,
    );
    lines.push(
      `    ${handlerName.toUpperCase()}_HANDLER.with(|slot| *slot.borrow_mut() = Some(Box::new(callback)));`,
    );
    lines.push("}");
    lines.push("");
    lines.push(`pub fn clear_${handlerName}() {`);
    lines.push(`    ${handlerName.toUpperCase()}_HANDLER.with(|slot| *slot.borrow_mut() = None);`);
    lines.push("}");
    lines.push("");
    lines.push("#[no_mangle]");
    lines.push(`pub extern "C" fn ${method.exportName}(${emitExportArgs(method.args)}) {`);
    lines.push(`    ${handlerName.toUpperCase()}_HANDLER.with(|slot| {`);
    lines.push("        let handler = slot.borrow();");
    lines.push("        let Some(callback) = handler.as_ref() else {");
    lines.push("            return;");
    lines.push("        };");
    lines.push(...emitDecodedArgs(method.args));
    if (method.args.length === 0) {
      lines.push("        callback();");
    } else {
      lines.push(`        callback(${method.args.map((_arg, index) => `arg${String(index)}`).join(", ")});`);
    }
    lines.push("    });");
    lines.push("}");
    lines.push("");
  });
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, `${lines.join("\n")}\n`, "utf8");
}
