import path from "node:path";

import { type GenerateContext, type GenerateStrategy, writeGeneratedFile } from "../../shared/core";
import { emitTypeScriptEnum, valuesForEnumSpec } from "../../shared/enum-generation";
import { canonicalEnumSpecs } from "../../shared/model/enum-specs";

export class BrowserHostEnumsStrategy implements GenerateStrategy {
  public readonly name = "browser-host-enums";

  public async run(context: GenerateContext): Promise<void> {
    const outputPath = path.join(context.repoRoot, "v2/browser-bridge/src/generated/fui-host.ts");
    const hostSpecs = canonicalEnumSpecs.filter((spec) => spec.source === "host");
    const generated = [
      "// Generated by v2/abi/generate.ts strategy browser-host-enums.",
      "// Do not edit by hand.",
      "",
      ...hostSpecs.map((spec) => emitTypeScriptEnum(
        spec,
        valuesForEnumSpec(
          spec,
          { enums: [], constants: [], functions: [] },
          { enums: [], constants: [], functions: [] },
        ),
      )),
      "",
    ].join("\n\n");
    await writeGeneratedFile(
      outputPath,
      generated,
      context.check,
      `${path.relative(process.cwd(), outputPath)} is stale. Run npm run generate:abi from v2/fui-rs.`,
    );
  }
}
