import { promises as fs } from "node:fs";
import path from "node:path";
import { type CHeader, parseCHeader } from "../../shared/c-header";
import { type GenerateContext, type GenerateStrategy, writeGeneratedFile } from "../../shared/core";
import { emitTypeScriptEnum, valuesForEnumSpec } from "../../shared/enum-generation";
import { canonicalEnumSpecs } from "../../shared/model/enum-specs";
import { parseFuiAsGeneratedFileOptions } from "./common";

function emitFuiAsEnumsFile(uiSource: CHeader, coreSource: CHeader): string {
  const blocks = [
    "// @ts-nocheck",
    "// Generated by v2/abi/generate.ts strategy fui-as-enums from v2/ui/include/effindom_ui.h and v2/core/include/effindom.h.",
    "// Includes SDK facade enum names backed by canonical ABI header values.",
    "// SDK-only facade enums remain in core/ffi.ts until they have a canonical ABI source.",
    "// Do not edit by hand.",
    "",
    ...canonicalEnumSpecs.map((spec) => emitTypeScriptEnum(spec, valuesForEnumSpec(spec, uiSource, coreSource))),
    "",
  ];
  return blocks.join("\n\n").replace(/\n{3,}/g, "\n\n");
}

export class FuiAsEnumsStrategy implements GenerateStrategy {
  public readonly name = "fui-as-enums";

  public async run(context: GenerateContext): Promise<void> {
    const options = parseFuiAsGeneratedFileOptions(context, "src/core/generated/UiEnums.ts");
    const uiSource = parseCHeader(await fs.readFile(path.join(context.repoRoot, "v2/ui/include/effindom_ui.h"), "utf8"));
    const coreSource = parseCHeader(await fs.readFile(path.join(context.repoRoot, "v2/core/include/effindom.h"), "utf8"));
    const generated = emitFuiAsEnumsFile(uiSource, coreSource);
    await writeGeneratedFile(
      options.outputPath,
      generated,
      context.check,
      `${options.outputPath} is stale. Run npm run generate:abi from v2/fui-as.`,
    );
  }
}
