import { emitAssemblyScriptHostExternal } from "../../shared/assemblyscript";
import { fuiFetchHostImports } from "../../shared/fui-fetch-host";
import { type GenerateContext, type GenerateStrategy, writeGeneratedFile } from "../../shared/core";
import { parseFuiAsGeneratedFileOptions } from "./common";

function emitFuiAsFetchHostFile(functions: readonly typeof fuiFetchHostImports[number][]): string {
  const blocks = [
    "// @ts-nocheck",
    "// Generated by v2/abi/generate.ts strategy fui-as-fetch-host from v2/abi/shared/fui-fetch-host.ts.",
    "// Includes only raw fui_fetch_host imports referenced by v2/fui-as Tier 3 code.",
    "// Do not edit by hand.",
    "",
    functions.map((item) => emitAssemblyScriptHostExternal("fui_fetch_host", item)).join("\n\n"),
    "",
  ];
  return blocks.join("\n").replace(/\n{3,}/g, "\n\n");
}

export class FuiAsFetchHostStrategy implements GenerateStrategy {
  public readonly name = "fui-as-fetch-host";

  public async run(context: GenerateContext): Promise<void> {
    const options = parseFuiAsGeneratedFileOptions(context, "src/core/generated/FetchHostAbi.ts");
    const generated = emitFuiAsFetchHostFile(fuiFetchHostImports);
    await writeGeneratedFile(
      options.outputPath,
      generated,
      context.check,
      `${options.outputPath} is stale. Run npm run generate:abi from v2/fui-as.`,
    );
  }
}
