import { emitAssemblyScriptHostExternal } from "../../shared/assemblyscript";
import { fuiHostImports, type FuiHostImport } from "../../shared/fui-host";
import { type GenerateContext, type GenerateStrategy, writeGeneratedFile } from "../../shared/core";
import { parseFuiAsGeneratedFileOptions, collectUsedHostImports } from "./common";

function emitFuiAsHostFile(functions: readonly FuiHostImport[]): string {
  const blocks = [
    "// @ts-nocheck",
    "// Generated by v2/abi/generate.ts strategy fui-as-host from v2/abi/shared/fui-host.ts.",
    "// Includes only raw fui_host imports referenced by v2/fui-as Tier 3 code.",
    "// Do not edit by hand.",
    "",
    functions.map((item) => emitAssemblyScriptHostExternal("fui_host", item)).join("\n\n"),
    "",
  ];
  return blocks.join("\n").replace(/\n{3,}/g, "\n\n");
}

export class FuiAsHostStrategy implements GenerateStrategy {
  public readonly name = "fui-as-host";

  public async run(context: GenerateContext): Promise<void> {
    const options = parseFuiAsGeneratedFileOptions(context, "src/core/generated/HostAbi.ts");
    const usedFunctions = await collectUsedHostImports(options.usageSourcePath, options.outputPath);
    const functions = fuiHostImports.filter((item) => usedFunctions.has(item.name));
    const generated = emitFuiAsHostFile(functions);
    await writeGeneratedFile(
      options.outputPath,
      generated,
      context.check,
      `${options.outputPath} is stale. Run npm run generate:abi from v2/fui-as.`,
    );
  }
}
