import { promises as fs } from "node:fs";
import path from "node:path";
import { emitAssemblyScriptExternal, collectUsedAssemblyScriptFfiImports, selectUsedFunctions } from "../../shared/assemblyscript";
import { type CFunction, parseCHeader } from "../../shared/c-header";
import { sourcePathForHeader, type GenerateContext, type GenerateStrategy, writeGeneratedFile } from "../../shared/core";
import { parseFuiAsUiOptions } from "./common";

function emitFuiAsUiFile(packageDir: string, headerPath: string, functions: readonly CFunction[]): string {
  const blocks = [
    "// @ts-nocheck",
    `// Generated by v2/abi/generate.ts strategy fui-as-ui from ${sourcePathForHeader(packageDir, headerPath)}.`,
    "// Includes only raw UI ABI imports referenced by v2/fui-as Tier 3 code.",
    "// Public SDK-facing enum aliases live in core/ffi.ts.",
    "// Do not edit by hand.",
    "",
    functions.map((fn) => emitAssemblyScriptExternal("effindom_v2_ui", fn)).join("\n\n"),
    "",
  ];
  return blocks.join("\n").replace(/\n{3,}/g, "\n\n");
}

export class FuiAsUiStrategy implements GenerateStrategy {
  public readonly name = "fui-as-ui";

  public async run(context: GenerateContext): Promise<void> {
    const options = parseFuiAsUiOptions(context);
    const source = await fs.readFile(options.headerPath, "utf8");
    const usedFunctions = await collectUsedAssemblyScriptFfiImports(
      options.usageSourcePath,
      options.outputPath,
      "ui_",
    );
    const functions = selectUsedFunctions(parseCHeader(source).functions, usedFunctions);
    const packageDir = path.join(context.repoRoot, "v2/fui-as");
    const generated = emitFuiAsUiFile(packageDir, options.headerPath, functions);
    await writeGeneratedFile(
      options.outputPath,
      generated,
      context.check,
      `${path.relative(process.cwd(), options.outputPath)} is stale. Run npm run generate:ui-abi from v2/fui-as.`,
    );
  }
}
